version: "3.7"

services:
  db:
    image: library/postgres:12
    environment:
      - POSTGRES_DB=welbex
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: ${PROJECT_NAME}Web
    volumes:
      - ./:/app
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    environment:
      DJANGO_ADMIN_USERNAME: admin
      DJANGO_ADMIN_PASSWORD: admin
      DJANGO_SETTINGS_FOLDER: WelbexTest
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}Nginx
    ports:
      - "8920:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/static
      - mediafiles:/app/media
    depends_on:
      - web


volumes:
  staticfiles:
    name: ${PROJECT_NAME}Staticfiles

  mediafiles:
    name: ${PROJECT_NAME}Mediafiles